name: Build Signed Android App & Bundle

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Generate Keystore
        run: |
          mkdir -p android/app
          keytool -genkey -v -keystore android/app/upload-keystore.jks -storepass MySecretPass123 -keypass MySecretPass123 -alias upload -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=POS, OU=IT, O=POS, L=City, S=State, C=US"

      - name: Create key.properties
        run: |
          echo "storePassword=MySecretPass123" > android/key.properties
          echo "keyPassword=MySecretPass123" >> android/key.properties
          echo "keyAlias=upload" >> android/key.properties
          echo "storeFile=upload-keystore.jks" >> android/key.properties

      - name: Install Dependencies
        run: flutter pub get

      # الخطوة السحرية لتنظيف ملف المكتبة من التعارض مع AGP 8.0
      - name: Fix blue_thermal_printer Manifest for AGP 8.0
        run: |
          sed -i 's/package="id.kakzaki.blue_thermal_printer"//g' /home/runner/.pub-cache/hosted/pub.dev/blue_thermal_printer-*/android/src/main/AndroidManifest.xml

      - name: Build APK
        run: flutter build apk --release

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - uses: actions/upload-artifact@v4
        with:
          name: direct-install-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: google-play-aab
          path: build/app/outputs/bundle/release/app-release.aab
